---
apiVersion: v1
kind: Service
metadata:
  name: multi-cluster-rs-pdx
  annotations:
    federation.tigera.io/serviceSelector:
      app == "multi-cluster-rs-pdx"
spec:
  ports:
  - port: 80
    name: web
    protocol: TCP
  clusterIP: None

---
apiVersion: v1
kind: Service
metadata:
  name: multi-cluster-rs-iad
  labels:
    app: multi-cluster-rs-iad
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: multi-cluster-rs-iad

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: multi-cluster-rs-iad
spec:
  selector:
    matchLabels:
      app: multi-cluster-rs-iad
  serviceName: "multi-cluster-rs-iad"
  replicas: 1
  template:
    metadata:
      labels:
        app: multi-cluster-rs-iad
    spec:
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: web
          mountPath: /usr/share/nginx/html
      volumes:
      - name: web
        hostPath:
          path: /mnt/data
          type: DirectoryOrCreate

